FROM golang:1.20-alpine

RUN apk add --no-cache --virtual build-dependencies git gcc build-base wget

WORKDIR /app

COPY go.mod go.sum /app/
RUN go mod download && go get github.com/githubnemo/CompileDaemon && go install github.com/githubnemo/CompileDaemon

COPY . /app/

EXPOSE 8080

CMD CompileDaemon --build="go build -o /api" --command="./../api"