version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app/
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - CGO_ENABLED=1
    env_file:
      - .env